name: CICD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - dev
  workflow_dispatch:

jobs:
  test-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install bun
        uses: oven-sh/setup-bun@v2

      - name: Install frontend dependencies
        working-directory: frontend
        run: |
          bun ci

      - name: Setup frontend env file
        working-directory: frontend
        run: |
          cp .env.example .env

      - name: Check frontend code validity
        working-directory: frontend
        run: |
          bun --bun run check

      - name: Check frontend code formatting
        if: github.ref != 'refs/heads/main'
        continue-on-error: true
        working-directory: frontend
        run: |
          bun --bun run lint

  test-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache cargo
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin
            ~/.cargo/registry
            ~/.cargo/git
            backend/target
          key: ${{ runner.os }}-cargo-check-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-check-${{ hashFiles('**/Cargo.lock') }}
            ${{ runner.os }}-cargo

      - name: Install backend dependencies
        working-directory: backend
        run: |
          cargo fetch

      - name: Setup backend env file
        working-directory: backend
        run: |
          cp .env.example .env

      - name: Check backend code validity
        working-directory: backend
        run: |
          cargo check

      - name: Check backend code formatting
        if: github.ref != 'refs/heads/main'
        continue-on-error: true
        working-directory: backend
        run: |
          cargo fmt --check

  test-terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup terraform
        uses: hashicorp/setup-terraform@v3

      - name: Configure aws credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1

      - name: Init terraform
        working-directory: terraform
        run: |
          terraform init -input=false

      - name: Check terraform code validity
        working-directory: terraform
        run: |
          terraform validate -no-color

      - name: Check terraform code formatting
        if: github.ref != 'refs/heads/main'
        continue-on-error: true
        working-directory: terraform
        run: |
          terraform fmt -check -no-color

  build-app:
    if : false
    # if: github.ref == 'refs/heads/main'
    needs:
      - test-frontend
      - test-backend
      - test-terraform
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install bun
        uses: oven-sh/setup-bun@v2

      - name: Install frontend dependencies
        working-directory: frontend
        run: |
          bun --bun ci

      - name: Setup frontend env file
        working-directory: frontend
        run: |
          cp .env.example .env

      - name: Build frontend
        working-directory: frontend
        run: |
          bun --bun run build

      - name: Cache Cargo
        id: cache-cargo
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin
            ~/.cargo/registry
            ~/.cargo/git
            backend/target
          key: ${{ runner.os }}-cargo-build-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-build
            ${{ runner.os }}-cargo

      - name: Install cargo lambda
        run: |
          if ! cargo lambda --version
          then
              cargo install cargo-lambda
              echo "cargo lambda is situated at : " $(which cargo-lambda)
          fi

      - name: Setup backend env file
        working-directory: backend
        run: |
          cp .env.example .env

      - name: Build api lambda
        working-directory: backend
        run: |
          npm install -g @ziglang/cli
          cargo lambda build --bin apilambda --target aarch64-unknown-linux-gnu --release --lambda-dir ./cargo_lambda_build_result --flatten apilambda --output-format zip --include certs --include migrations

      - name: Upload build-app artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-app-files
          path: |
            frontend/build/
            backend/cargo_lambda_build_result/bootstrap.zip
          retention-days: 1
          overwrite: true
          include-hidden-files: true

      - name: Always save cargo cache
        if: always() && steps.cache-cargo.outputs.cache-hit != 'true'
        uses: actions/cache/save@v4
        with:
          key: ${{ runner.os }}-cargo-build-${{ hashFiles('**/Cargo.lock') }}
          path: |
            ~/.cargo/bin
            ~/.cargo/registry
            ~/.cargo/git
            backend/target

  deploy-app:
    if : false
    # if: github.ref == 'refs/heads/main'
    needs:
      - build-app
    concurrency:
      group: deployment
      cancel-in-progress: true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download build-app artifacts
        uses: actions/download-artifact@v5
        with:
          name: build-app-files
          path: ./

      - name: Setup terraform
        uses: hashicorp/setup-terraform@v3

      - name: Configure aws credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1

      - name: Init terraform
        working-directory: terraform
        run: |
          terraform init -input=false -no-color
      
      - name: Deploy on aws
        working-directory: terraform
        env:
          TF_VAR_s3_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          TF_VAR_s3_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          TF_VAR_acm_certificate_arn: ${{ secrets.ACM_CERTIFICATE_ARN }}
          TF_VAR_cloudflare_api_token: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          TF_VAR_jwt_secret: ${{ secrets.JWT_SECRET }}
          TF_VAR_rds_dtbsname: ${{ secrets.RDS_DATABASE_NAME }}
          TF_VAR_rds_username: ${{ secrets.RDS_USERNAME }}
          TF_VAR_rds_password: ${{ secrets.RDS_PASSWORD }}
          TF_VAR_mail_from: ${{ secrets.MAIL_FROM }}
          TF_VAR_mail_user: ${{ secrets.MAIL_USER }}
          TF_VAR_mail_password: ${{ secrets.MAIL_PASSWORD }}
          TF_VAR_discord_webhook_url: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: |
          terraform apply -input=false -no-color -auto-approve
