name: Destroy aws architecture

on:
  workflow_dispatch:

jobs:
  destroy-aws-architecture:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure aws credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1

      - name: Setup terraform
        uses: hashicorp/setup-terraform@v3

      - name: Init terraform
        working-directory: terraform
        run: |
          terraform init -input=false -no-color

      - name: Fake terraform data
        run: |
          # terraform needs to compute some stuff before destroying
          # so we're creating fake data for that.
          mkdir --parents backend/cargo_lambda_build_result
          touch backend/cargo_lambda_build_result/bootstrap.zip

      - name: Destroy aws architecture
        working-directory: terraform
        env:
          TF_VAR_s3_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          TF_VAR_s3_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          TF_VAR_acm_certificate_arn: ${{ secrets.ACM_CERTIFICATE_ARN }}
          TF_VAR_cloudflare_api_token: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          TF_VAR_jwt_secret: ${{ secrets.JWT_SECRET }}
          TF_VAR_rds_dtbsname: ${{ secrets.RDS_DATABASE_NAME }}
          TF_VAR_rds_username: ${{ secrets.RDS_USERNAME }}
          TF_VAR_rds_password: ${{ secrets.RDS_PASSWORD }}
          TF_VAR_mail_from: ${{ secrets.MAIL_FROM }}
          TF_VAR_mail_user: ${{ secrets.MAIL_USER }}
          TF_VAR_mail_password: ${{ secrets.MAIL_PASSWORD }}
          TF_VAR_discord_webhook_url: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: |
          terraform destroy -input=false -no-color -auto-approve
